#!/usr/bin/env bash
#------------------------------------------------------------------------------
# generate-os-coverage.sh - render the per-major OS coverage matrix (Phase 6).
#
# Sources lib/os-profile.sh (the canon) and writes a deterministic
# RESULTS-coverage.md - the design plan sec 6 matrix, derived purely from the
# profile helpers (never hand-edited). No network, no container; runs anywhere.
#
# Usage:   bash tests/os-coverage/generate-os-coverage.sh [output.md]
#   default output: tests/os-coverage/RESULTS-coverage.md (beside this script)
#------------------------------------------------------------------------------
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJ_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OUT="${1:-${SCRIPT_DIR}/RESULTS-coverage.md}"

# shellcheck source=../../lib/os-profile.sh
. "${PROJ_DIR}/lib/os-profile.sh"

log() { printf '%s [os-coverage] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >&2; }

anon_cell() { osp_has_anon_repo "$1" && printf 'yes' || printf '**no**'; }
epel_cell() { osp_epel_is_live "$1" && printf 'live' || printf 'archive'; }

{
  printf '# RHEL-family OS coverage matrix\n\n'
  printf '> GENERATED by tests/os-coverage/generate-os-coverage.sh from\n'
  printf '> lib/os-profile.sh - do not hand-edit. Derived purely from the profile\n'
  printf '> canon; tests/t012_osprofile.sh asserts the canon agrees with the\n'
  printf '> acquisition libraries and the ENA matrix.\n\n'

  printf '| RHEL | tier | image | pull | pkgmgr | anon repo | EPEL | lifecycle |\n'
  printf '|:--|:--|:--|:--|:--|:--|:--|:--|\n'
  for m in 10 9 8 7 6; do
    printf '| %s | %s | \140%s\140 | %s | %s | %s | %s | %s |\n' \
      "${m}" "$(osp_tier "${m}")" "$(osp_image "${m}")" "$(osp_pull_constraint "${m}")" \
      "$(osp_pkgmgr "${m}")" "$(anon_cell "${m}")" "$(epel_cell "${m}")" "$(osp_lifecycle "${m}")"
  done
  printf '\n'

  printf '## entitled mode (kernel-devel obtainable in every major)\n\n'
  printf '| RHEL | entitled repo family | kernel-devel repo |\n'
  printf '|:--|:--|:--|\n'
  for m in 10 9 8 7 6; do
    printf '| %s | \140%s\140 | \140%s\140 |\n' "${m}" "$(osp_entitled_repo "${m}")" "$(osp_kdevel_repo "${m}")"
  done
  printf '\n'

  printf '## tier semantics\n\n'
  printf -- '- **A - current** (10 / 9 / 8): \140ubi-init\140, floating tag, dnf, \140ubi-*\140 anon repos.\n'
  printf -- '- **B - settled** (7): \140ubi7/ubi-init\140 pulled by **fixed tag \1407.9-88\140** (floating-tag signature rejected), yum, anon repos incl RHSCL.\n'
  printf -- '- **C - constrained** (6): \140rhel6/rhel\140 (non-UBI), **no anonymous repo** (base image only), EPEL **archive-only**. Entitled \140rhel-6-server-rpms\140 passes through and kernel-devel is obtainable - so C is about the *missing anon repo*, not unbuildability.\n'
  printf '\n_EPEL is a live capability only on 8/9/10; 7 is the EOL archive and 6 is the OL6-style archive-only special case._\n'
} > "${OUT}"
log "wrote ${OUT}"
