@{
    RootModule        = 'powershell.psm1'
    ModuleVersion     = '1.0.0'
    GUID              = 'deaf9b50-4be5-53b3-9efa-1c113263f6f5'
    Description       = 'Canonical shared PowerShell helpers (reference-code canon). Public functions are vendored into consumers; Private are internal dependencies. The module wrapper is test scaffolding, not a vendored unit.'
    PowerShellVersion = '5.1'
    FunctionsToExport = @(
        'Assert-PowerShellCompatibility'
        'Disable-DebugTraceFileOutput'
        'Enable-AutoExportOnPhaseFailure'
        'Enable-DebugTraceFileOutput'
        'Export-DebugTraceJson'
        'Format-DebugFailure'
        'Format-Elapsed'
        'Get-DebugTraceFileOutputStatus'
        'Get-PhaseElapsedTag'
        'Set-DebugStep'
        'Set-TlsSecurityProtocol'
        'Set-Utf8PipelineEncoding'
        'Show-PowerShellEnvironment'
        'Start-DebugTrace'
        'Stop-DebugTrace'
        'Write-Caution'
        'Write-DebugFailureReport'
        'Write-Detail'
        'Write-Fail'
        'Write-Ok'
        'Write-PhaseFooter'
        'Write-PhaseHeader'
        'Write-Skip'
        'Write-Step'
        'Get-SevenZipPath'
        'Get-LatestSevenZipUrl'
        'Install-SevenZipFallback'
        'Invoke-WebRequestWithRetry'
        'Wait-WithJitter'
        'Initialize-RuntimeDirectories'
        'Invoke-CleanupDirectories'
        'Resolve-RelativeToScript'
        'Test-DangerousPath'
        'Add-ErrorJsonlEntry'
        'Show-PhaseSummary'
        'Write-SubSection'
        'Save-CanonicalJsonFile'
        'ConvertTo-CanonicalJson'
        'ConvertFrom-CanonicalJson'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
}
