#!/usr/bin/env python3
"""T29: digest-format boundary unit test (offline).

Config Schema v3.0 stores ``PatchBaseline.Lines[].Digest`` (SHA-1) and
``.Sha256`` exactly as the Microsoft Update Catalog DownloadDialog serves
them: **base64**. ``Get-FileHash`` yields **hex**. Until r11.44 the
verification path ``Test-PatchIntegrity`` compared the two formats
directly, so EVERY real download failed verification with
"SHA-256 content mismatch" (the 2026-07-02 audit's F4 E2E blocker).

r11.44 introduces the single conversion boundary
``ConvertTo-HexDigestString`` and wires the SHA-1 ``Digest`` (the
cross-surface primary key per the reference architecture memo) into the
P04 ``ExpectedHashes`` seeding. This test pins both halves:

1. **Byte-level round-trip vs an independent implementation.** Python
   computes SHA-1/SHA-256 of a locally generated byte blob, base64-encodes
   them (the Catalog wire format), pushes them through the PowerShell
   boundary function via the TestHarness REPL, and asserts the result
   equals Python's own hex digest.
2. **Live-data vector.** The 2026-07-02 capture of KB5095966 proved the
   Catalog base64 digest decodes to the filename-embedded SHA-1; that
   exact pair is pinned here as a regression vector.
3. **Hex pass-through + rejection paths.** Hex input returns unchanged
   (lowercased); non-hex/non-base64 input and wrong-length base64 throw.
4. **Static wiring guard.** The script text must (a) normalize BOTH
   expected hashes through the boundary function inside
   ``Test-PatchIntegrity`` and (b) seed BOTH ``'sha-1'`` (from
   ``Line.Digest``) and ``'sha-256'`` (from ``Line.Sha256``) in the P04
   ExpectedHashes block -- so the fix cannot silently regress to a bare
   ``.ToLower()`` comparison or drop the primary-key wiring.

Run from the project root:

    python3 tests/patch_integrity_digest_test.py
"""
from __future__ import annotations

import base64
import hashlib
import pathlib
import re
import sys

TESTS_DIR = pathlib.Path(__file__).resolve().parent

sys.path.insert(0, str(TESTS_DIR))
from common.ps_invoke import PSSession, PSHarnessError  # type: ignore  # noqa: E402

SCRIPT_PATH = TESTS_DIR.parent / "Update-WindowsServerIso.ps1"

PASS = "  PASS"
FAIL = "  FAIL"

# Live-captured regression vector (Microsoft Update Catalog, 2026-07-02):
# 2026-06 Setup Dynamic Update KB5095966, x64 .cab. The DownloadDialog
# base64 digest decodes to exactly the filename-embedded SHA-1.
LIVE_B64_SHA1 = "xi/9YT/XBI6aJxV66uHoMvZUPAY="
LIVE_HEX_SHA1 = "c62ffd613fd7048e9a27157aeae1e832f6543c06"


def check(label: str, ok: bool, detail: str, p: int, f: int) -> tuple[int, int]:
    if ok:
        print(f"{PASS}  {label}: {detail}")
        return p + 1, f
    print(f"{FAIL}  {label}: {detail}")
    return p, f + 1


def main() -> int:
    passed = 0
    failed = 0

    blob = b"UpdateWsi digest-format boundary test blob 2026-07-02\r\n" * 64
    py_sha1_hex = hashlib.sha1(blob).hexdigest()
    py_sha256_hex = hashlib.sha256(blob).hexdigest()
    b64_sha1 = base64.b64encode(hashlib.sha1(blob).digest()).decode("ascii")
    b64_sha256 = base64.b64encode(hashlib.sha256(blob).digest()).decode("ascii")

    with PSSession(SCRIPT_PATH) as ps:
        # 1. base64 -> hex round-trip vs Python (both bit widths)
        got = ps.invoke("ConvertTo-HexDigestString", Value=b64_sha1, HashBits=160)
        passed, failed = check(
            "sha-1 base64->hex round-trip vs python",
            got == py_sha1_hex,
            f"got={got!r} expected={py_sha1_hex!r}",
            passed, failed)

        got = ps.invoke("ConvertTo-HexDigestString", Value=b64_sha256, HashBits=256)
        passed, failed = check(
            "sha-256 base64->hex round-trip vs python",
            got == py_sha256_hex,
            f"got={got!r} expected={py_sha256_hex!r}",
            passed, failed)

        # 2. live-captured Catalog vector (KB5095966)
        got = ps.invoke("ConvertTo-HexDigestString", Value=LIVE_B64_SHA1, HashBits=160)
        passed, failed = check(
            "live Catalog vector KB5095966 (base64 digest == filename SHA-1)",
            got == LIVE_HEX_SHA1,
            f"got={got!r} expected={LIVE_HEX_SHA1!r}",
            passed, failed)

        # 3a. hex pass-through (uppercase in -> lowercase out)
        got = ps.invoke("ConvertTo-HexDigestString",
                        Value=py_sha256_hex.upper(), HashBits=256)
        passed, failed = check(
            "hex pass-through (case-normalized)",
            got == py_sha256_hex,
            f"got={got!r}",
            passed, failed)

        # 3b. garbage input throws
        try:
            ps.invoke("ConvertTo-HexDigestString",
                      Value="not-a-digest-at-all!!", HashBits=256)
            passed, failed = check("garbage input rejected", False,
                                   "no exception raised", passed, failed)
        except PSHarnessError as exc:
            passed, failed = check(
                "garbage input rejected",
                "neither" in str(exc),
                f"error={str(exc)[:120]!r}",
                passed, failed)

        # 3c. wrong-length base64 throws (a SHA-1 b64 declared as 256-bit)
        try:
            ps.invoke("ConvertTo-HexDigestString", Value=b64_sha1, HashBits=256)
            passed, failed = check("wrong-length base64 rejected", False,
                                   "no exception raised", passed, failed)
        except PSHarnessError as exc:
            passed, failed = check(
                "wrong-length base64 rejected",
                "byte" in str(exc),
                f"error={str(exc)[:120]!r}",
                passed, failed)

    # 4. static wiring guard over the script text
    text = SCRIPT_PATH.read_text(encoding="utf-8-sig")

    passed, failed = check(
        "Test-PatchIntegrity normalizes sha-1 through the boundary",
        re.search(r"\$expSha1\s*=\s*ConvertTo-HexDigestString\b[^\r\n]*-HashBits 160",
                  text) is not None,
        "expected `$expSha1 = ConvertTo-HexDigestString ... -HashBits 160`",
        passed, failed)

    passed, failed = check(
        "Test-PatchIntegrity normalizes sha-256 through the boundary",
        re.search(r"\$expSha256\s*=\s*ConvertTo-HexDigestString\b[^\r\n]*-HashBits 256",
                  text) is not None,
        "expected `$expSha256 = ConvertTo-HexDigestString ... -HashBits 256`",
        passed, failed)

    passed, failed = check(
        "no bare .ToLower() comparison remains on ExpectedHashes",
        re.search(r"\$ExpectedHashes\['sha-(?:1|256)'\]\.ToLower\(\)", text) is None,
        "a direct `$ExpectedHashes[...].ToLower()` comparison resurfaced",
        passed, failed)

    passed, failed = check(
        "P04 seeding wires Line.Digest into ExpectedHashes['sha-1']",
        re.search(r"\$expectedHashes\['sha-1'\]\s*=\s*\[string\]\$p\.Digest",
                  text) is not None,
        "expected `$expectedHashes['sha-1'] = [string]$p.Digest`",
        passed, failed)

    passed, failed = check(
        "P04 seeding still wires Line.Sha256 into ExpectedHashes['sha-256']",
        re.search(r"\$expectedHashes\['sha-256'\]\s*=\s*\$p\.Sha256",
                  text) is not None,
        "expected `$expectedHashes['sha-256'] = $p.Sha256`",
        passed, failed)

    print()
    print(f"  Summary: {passed} passed, {failed} failed, {passed + failed} total")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
