#!/usr/bin/env python3
"""T29: digest-format boundary unit test (offline).

Config Schema v3.0 stores ``PatchBaseline.Lines[].Digest`` (SHA-1) and
``.Sha256`` exactly as the Microsoft Update Catalog DownloadDialog serves
them: **base64**. ``Get-FileHash`` yields **hex**. Until r11.44 the
verification path ``Test-PatchIntegrity`` compared the two formats
directly, so EVERY real download failed verification with
"SHA-256 content mismatch" (the 2026-07-02 audit's F4 E2E blocker).

r11.44 introduces the single conversion boundary
``ConvertTo-HexDigestString`` and wires the SHA-1 ``Digest`` (the
cross-surface primary key per the reference architecture memo) into the
P04 ``ExpectedHashes`` seeding. This test pins both halves:

1. **Byte-level round-trip vs an independent implementation.** Python
   computes SHA-1/SHA-256 of a locally generated byte blob, base64-encodes
   them (the Catalog wire format), pushes them through the PowerShell
   boundary function via the TestHarness REPL, and asserts the result
   equals Python's own hex digest.
2. **Live-data vector.** The 2026-07-02 capture of KB5095966 proved the
   Catalog base64 digest decodes to the filename-embedded SHA-1; that
   exact pair is pinned here as a regression vector.
3. **Hex pass-through + rejection paths.** Hex input returns unchanged
   (lowercased); non-hex/non-base64 input and wrong-length base64 throw.
4. **Static wiring guard (REPLACED at r12.00, Schema 4.0).** The old
   guard pinned direct flat-field reads (``$p.Digest`` / ``$p.Sha256``)
   in the P04 seeding block. r12 makes ``PatchBaseline.Lines[].Integrity``
   the canonical integrity surface and keeps the flat ``Digest`` /
   ``Sha256`` fields only as ``Compatibility.LegacyFieldsRetained``; the
   runtime therefore reads every baseline hash through the single
   accessor ``Get-BaselineHashValue -Line ... -Algorithm Sha1|Sha256``,
   which serves both surfaces (flat legacy fields honoured for retained
   v3 data, ``Integrity.<Alg>.Value`` for canonical v4 data). The guard
   now pins: (a) BOTH expected hashes are normalized through the boundary
   function inside ``Test-PatchIntegrity``; (b) the P04/runtime seeding
   goes through ``Get-BaselineHashValue`` and no direct ``$p.Digest`` /
   ``$p.Sha256`` seeding remains; (c) the accessor itself reads the
   canonical ``Integrity.<Alg>.Value`` node and guards the flat fields as
   the retained-legacy path. The data-side declaration (every Line
   carries ``Integrity`` with valid algorithm nodes) is T43
   ``line_integrity_declaration_test.py``; this test keeps the
   script-side wiring and the format boundary.

Run from the project root:

    python3 tests/patch_integrity_digest_test.py
"""
from __future__ import annotations

import base64
import hashlib
import pathlib
import re
import sys

TESTS_DIR = pathlib.Path(__file__).resolve().parent

sys.path.insert(0, str(TESTS_DIR))
from common.ps_invoke import PSSession, PSHarnessError  # type: ignore  # noqa: E402

SCRIPT_PATH = TESTS_DIR.parent / "Update-WindowsServerIso.ps1"

PASS = "  PASS"
FAIL = "  FAIL"

# Live-captured regression vector (Microsoft Update Catalog, 2026-07-02):
# 2026-06 Setup Dynamic Update KB5095966, x64 .cab. The DownloadDialog
# base64 digest decodes to exactly the filename-embedded SHA-1.
LIVE_B64_SHA1 = "xi/9YT/XBI6aJxV66uHoMvZUPAY="
LIVE_HEX_SHA1 = "c62ffd613fd7048e9a27157aeae1e832f6543c06"


def check(label: str, ok: bool, detail: str, p: int, f: int) -> tuple[int, int]:
    if ok:
        print(f"{PASS}  {label}: {detail}")
        return p + 1, f
    print(f"{FAIL}  {label}: {detail}")
    return p, f + 1


def main() -> int:
    passed = 0
    failed = 0

    blob = b"UpdateWsi digest-format boundary test blob 2026-07-02\r\n" * 64
    py_sha1_hex = hashlib.sha1(blob).hexdigest()
    py_sha256_hex = hashlib.sha256(blob).hexdigest()
    b64_sha1 = base64.b64encode(hashlib.sha1(blob).digest()).decode("ascii")
    b64_sha256 = base64.b64encode(hashlib.sha256(blob).digest()).decode("ascii")

    with PSSession(SCRIPT_PATH) as ps:
        # 1. base64 -> hex round-trip vs Python (both bit widths)
        got = ps.invoke("ConvertTo-HexDigestString", Value=b64_sha1, HashBits=160)
        passed, failed = check(
            "sha-1 base64->hex round-trip vs python",
            got == py_sha1_hex,
            f"got={got!r} expected={py_sha1_hex!r}",
            passed, failed)

        got = ps.invoke("ConvertTo-HexDigestString", Value=b64_sha256, HashBits=256)
        passed, failed = check(
            "sha-256 base64->hex round-trip vs python",
            got == py_sha256_hex,
            f"got={got!r} expected={py_sha256_hex!r}",
            passed, failed)

        # 2. live-captured Catalog vector (KB5095966)
        got = ps.invoke("ConvertTo-HexDigestString", Value=LIVE_B64_SHA1, HashBits=160)
        passed, failed = check(
            "live Catalog vector KB5095966 (base64 digest == filename SHA-1)",
            got == LIVE_HEX_SHA1,
            f"got={got!r} expected={LIVE_HEX_SHA1!r}",
            passed, failed)

        # 3a. hex pass-through (uppercase in -> lowercase out)
        got = ps.invoke("ConvertTo-HexDigestString",
                        Value=py_sha256_hex.upper(), HashBits=256)
        passed, failed = check(
            "hex pass-through (case-normalized)",
            got == py_sha256_hex,
            f"got={got!r}",
            passed, failed)

        # 3b. garbage input throws
        try:
            ps.invoke("ConvertTo-HexDigestString",
                      Value="not-a-digest-at-all!!", HashBits=256)
            passed, failed = check("garbage input rejected", False,
                                   "no exception raised", passed, failed)
        except PSHarnessError as exc:
            passed, failed = check(
                "garbage input rejected",
                "neither" in str(exc),
                f"error={str(exc)[:120]!r}",
                passed, failed)

        # 3c. wrong-length base64 throws (a SHA-1 b64 declared as 256-bit)
        try:
            ps.invoke("ConvertTo-HexDigestString", Value=b64_sha1, HashBits=256)
            passed, failed = check("wrong-length base64 rejected", False,
                                   "no exception raised", passed, failed)
        except PSHarnessError as exc:
            passed, failed = check(
                "wrong-length base64 rejected",
                "byte" in str(exc),
                f"error={str(exc)[:120]!r}",
                passed, failed)

    # 4. static wiring guard over the script text
    text = SCRIPT_PATH.read_text(encoding="utf-8-sig")

    passed, failed = check(
        "Test-PatchIntegrity normalizes sha-1 through the boundary",
        re.search(r"\$expSha1\s*=\s*ConvertTo-HexDigestString\b[^\r\n]*-HashBits 160",
                  text) is not None,
        "expected `$expSha1 = ConvertTo-HexDigestString ... -HashBits 160`",
        passed, failed)

    passed, failed = check(
        "Test-PatchIntegrity normalizes sha-256 through the boundary",
        re.search(r"\$expSha256\s*=\s*ConvertTo-HexDigestString\b[^\r\n]*-HashBits 256",
                  text) is not None,
        "expected `$expSha256 = ConvertTo-HexDigestString ... -HashBits 256`",
        passed, failed)

    passed, failed = check(
        "no bare .ToLower() comparison remains on ExpectedHashes",
        re.search(r"\$ExpectedHashes\['sha-(?:1|256)'\]\.ToLower\(\)", text) is None,
        "a direct `$ExpectedHashes[...].ToLower()` comparison resurfaced",
        passed, failed)

    passed, failed = check(
        "baseline-line seeding goes through the single accessor (Sha1)",
        re.search(r"\$sha1\s*=\s*Get-BaselineHashValue\s+-Line\s+\$\w+\s+-Algorithm\s+Sha1",
                  text) is not None,
        "expected `$sha1 = Get-BaselineHashValue -Line ... -Algorithm Sha1`",
        passed, failed)

    passed, failed = check(
        "baseline-line seeding goes through the single accessor (Sha256)",
        re.search(r"\$sha256\s*=\s*Get-BaselineHashValue\s+-Line\s+\$\w+\s+-Algorithm\s+Sha256",
                  text) is not None,
        "expected `$sha256 = Get-BaselineHashValue -Line ... -Algorithm Sha256`",
        passed, failed)

    passed, failed = check(
        "no direct flat-field seeding of a baseline Line remains",
        re.search(r"\$expectedHashes\['sha-(?:1|256)'\]\s*=\s*(?:\[string\])?\$p\.(?:Digest|Sha256)",
                  text) is None,
        "a direct `$p.Digest` / `$p.Sha256` ExpectedHashes seeding resurfaced",
        passed, failed)

    passed, failed = check(
        "accessor reads the canonical Integrity.<Alg>.Value node",
        "function Get-BaselineHashValue" in text
        and re.search(r"\$Line\.Integrity\b", text) is not None
        and re.search(r"\$node\.Value\b", text) is not None,
        "Get-BaselineHashValue does not read Integrity.<Alg>.Value",
        passed, failed)

    passed, failed = check(
        "accessor guards the flat fields as the retained-legacy path",
        re.search(r"PSObject\.Properties\['Digest'\]", text) is not None
        and re.search(r"PSObject\.Properties\['Sha256'\]", text) is not None,
        "flat legacy Digest/Sha256 path missing from the accessor",
        passed, failed)

    print()
    print(f"  Summary: {passed} passed, {failed} failed, {passed + failed} total")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
