#!/usr/bin/env bash
#==============================================================================
# tests/t022_ol10epel.sh - OL10 developer-EPEL discover/verify/finalize
#
# OL10's developer-EPEL repo is versioned per update release (baseurl
# .../OL10/<N>/developer/EPEL/..., section [ol10_u<N>_developer_EPEL]) and the
# shipped oracle-epel-ol10.repo can lag or lead the running minor (measured
# 2026-07-16: oracle-epel-release-el10 1.0-2 shipped u0, 1.0-6 ships u1, and a
# 10.2 system still carries u1 because /OL10/2/developer/EPEL/ was HTTP 404).
# install-ena-driver.sh therefore discovers candidates from BOTH the shipped
# repo file and the running minor, verifies each against the LIVE yum server
# (reachable AND offering dkms), and finalizes: enable a live shipped section,
# explicitly disable dead shipped sections, or materialize a DISPOSABLE repo
# file for a constructed-only winner (user adjudications D1/D2/D3, 2026-07-16).
#
# This tier is host-runnable and self-contained (no network, no container):
#   (structural)  the mechanism exists, is OL10-gated, probes for dkms (not
#                 just repomd), never regrows the hard-coded u1 literal, and
#                 wires the disposable cleanup after dkms provisioning;
#   (behavioural) the pure pieces -- URL expansion, repo-file candidate
#                 parsing, selection order -- run against fixtures copied from
#                 the REAL oracle-epel-release-el10 repo-file shapes, and the
#                 full orchestrator runs with a stubbed probe to exercise the
#                 shipped-enable, dead-disable, disposable, and all-dead paths.
# The live-server probe itself is container-FT / build-host territory
# (validated in an OL10 chroot against yum.oracle.com on 2026-07-16).
#==============================================================================
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJ="$(cd "${HERE}/.." && pwd)"
# shellcheck source=lib/assert.sh
. "${HERE}/lib/assert.sh"
INST="${PROJ}/install-ena-driver.sh"

inst="$(cat "${INST}")"

# ---- structural: the mechanism exists and is correctly scoped --------------
assert_match "${inst}" 'setup_epel_ol10\(\) \{' \
  "ol10-epel: setup_epel_ol10() orchestrator is defined"
assert_match "${inst}" '_ol10_epel_probe\(\) \{' \
  "ol10-epel: _ol10_epel_probe() is defined"
assert_match "${inst}" '_ol10_epel_select\(\) \{' \
  "ol10-epel: _ol10_epel_select() is defined"
assert_match "${inst}" 'cleanup_ol10_epel_disposable\(\) \{' \
  "ol10-epel: cleanup_ol10_epel_disposable() is defined"

# The probe must verify PACKAGE availability, not just repo reachability (D1),
# through core dnf (no plugin commands), and must not silently skip dead repos.
assert_match "${inst}" 'list available dkms' \
  "ol10-epel: probe verifies dkms availability (not repomd reachability alone)"
assert_match "${inst}" '--repofrompath=olawsprobe' \
  "ol10-epel: probe uses core-dnf --repofrompath (no plugin dependency)"
assert_match "${inst}" 'skip_if_unavailable=0' \
  "ol10-epel: probe forces an error (not a silent skip) on a dead repo"

# Regression pins: the hard-coded u1 wiring must never regrow (the silent
# "No match for argument: dkms" failure mode at every OL10 update rename).
if grep -Eq "sed -i '/\^\\\\\[ol10_u1_developer_EPEL" "${INST}"; then
  t_fail "ol10-epel: hard-coded [ol10_u1_developer_EPEL] sed is gone"
else
  t_pass "ol10-epel: hard-coded [ol10_u1_developer_EPEL] sed is gone"
fi
if grep -Fq '_epel_section="ol10_u1_developer_EPEL"' "${INST}"; then
  t_fail "ol10-epel: hard-coded u1 section assignment is gone"
else
  t_pass "ol10-epel: hard-coded u1 section assignment is gone"
fi

# OL10 must bypass the enabled-only early return (an enabled shipped section
# can still be DEAD there), and OL6-9 must keep it (OS isolation).
assert_match "${inst}" '"\$\{osmajor\}" != "10" \]\] && yum repolist enabled' \
  "ol10-epel: setup_epel enabled-only early return is bypassed on OL10 only"

# The BUILDTEST container path must use the same mechanism and fail loudly.
assert_match "${inst}" 'setup_epel_ol10 \|\| die "ENA_BUILDTEST' \
  "ol10-epel: ENA_BUILDTEST OL10 path routes through setup_epel_ol10 and dies on verification miss"

# Disposable lifecycle: gpg-checked content, single composed write, cleanup
# wired right after the dkms provisioning step (D2).
assert_match "${inst}" 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle' \
  "ol10-epel: disposable repo content is gpg-checked with the Oracle key"
assert_match "${inst}" 'DISPOSABLE -- generated by install-ena-driver.sh' \
  "ol10-epel: disposable repo carries the provenance marker header"
assert_match "${inst}" 'use_dkms=0[[:space:]]*$' \
  "ol10-epel: plain-make degradation is preserved (context anchor)"
if grep -A10 'if ! yum install -y dkms; then' "${INST}" | grep -q 'cleanup_ol10_epel_disposable'; then
  t_pass "ol10-epel: disposable cleanup is wired after the dkms provisioning step"
else
  t_fail "ol10-epel: disposable cleanup is wired after the dkms provisioning step"
fi

# ---- behavioural: extract the REAL functions and exercise fixtures ---------
# Extraction (not reimplementation) so the tier cannot drift from the script.
_extract() { sed -n "/^$1() {/,/^}/p" "${INST}"; }
ext_ok=1
for fn in _ol10_epel_expand_url _ol10_epel_file_candidates _ol10_epel_select \
          _ol10_epel_set_enabled setup_epel_ol10 cleanup_ol10_epel_disposable; do
  body="$(_extract "${fn}")"
  if [[ -z "${body}" ]]; then
    t_fail "ol10-epel: extracted ${fn} from the installer"
    ext_ok=0
    continue
  fi
  eval "${body}"
done
[[ ${ext_ok} -eq 1 ]] && t_pass "ol10-epel: all six functions extracted verbatim from the installer"

if [[ ${ext_ok} -eq 1 ]]; then
  log() { :; }
  # Consumed inside the eval'd installer functions (invisible to ShellCheck).
  # shellcheck disable=SC2034
  ENA_BUILDTEST=0
  # shellcheck disable=SC2034
  INSECURE_TLS=0

  tdir="$(mktemp -d)"
  trap 'rm -rf "${tdir}"' EXIT
  OL10_EPEL_REPO_FILE="${tdir}/oracle-epel-ol10.repo"
  OL10_EPEL_DISPOSABLE=""

  # Fixture mirrors the REAL shipped shapes: the verbatim u1 section from
  # oracle-epel-release-el10 1.0-6 plus a leftover u0 (1.0-2 shape) and an
  # unrelated section that must be ignored.
  cat > "${OL10_EPEL_REPO_FILE}" <<'EOF'
[ol10_u0_developer_EPEL]
name=Oracle Linux $releasever.0 EPEL Packages for Development ($basearch)
baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL10/0/developer/EPEL/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=1

[ol10_u1_developer_EPEL]
name=Oracle Linux $releasever.1 EPEL Packages for Development ($basearch)
baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL10/1/developer/EPEL/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=1

[some_other_repo]
baseurl=https://example.com/other/
enabled=1
EOF

  arch="$(uname -m)"
  # (b1) URL expansion: $ociregion -> "", $ocidomain -> oracle.com, $basearch.
  # shellcheck disable=SC2016  # the LITERAL Oracle repo-file variable form is the fixture
  got="$(_ol10_epel_expand_url 'https://yum$ociregion.$ocidomain/repo/OracleLinux/OL10/2/developer/EPEL/$basearch/')"
  assert_eq "https://yum.oracle.com/repo/OracleLinux/OL10/2/developer/EPEL/${arch}/" "${got}" \
    "ol10-epel: expand_url resolves the Oracle repo-file variables (AWS scope)"

  # (b2) candidate parsing: exactly the two developer-EPEL sections, expanded.
  got="$(_ol10_epel_file_candidates)"
  want="ol10_u0_developer_EPEL	https://yum.oracle.com/repo/OracleLinux/OL10/0/developer/EPEL/${arch}/
ol10_u1_developer_EPEL	https://yum.oracle.com/repo/OracleLinux/OL10/1/developer/EPEL/${arch}/"
  assert_eq "${want}" "${got}" \
    "ol10-epel: file candidates = the two developer-EPEL sections (unrelated section ignored), URLs expanded"

  # (b3) selection order (D1) across the fixture verdict matrix.
  osminor=2
  got="$(printf 'ol10_u0_developer_EPEL\t0\nol10_u1_developer_EPEL\t1\nol10_u2_developer_EPEL\t1\n' | _ol10_epel_select)"
  assert_eq "ol10_u2_developer_EPEL" "${got}" \
    "ol10-epel: select prefers the verified self-minor candidate"
  got="$(printf 'ol10_u1_developer_EPEL\t1\nol10_u2_developer_EPEL\t0\n' | _ol10_epel_select)"
  assert_eq "ol10_u1_developer_EPEL" "${got}" \
    "ol10-epel: select falls back past a dead self-minor to the highest live u<N> (the 10.2 lag reality)"
  osminor=3
  got="$(printf 'ol10_u1_developer_EPEL\t1\nol10_u2_developer_EPEL\t1\n' | _ol10_epel_select)"
  assert_eq "ol10_u2_developer_EPEL" "${got}" \
    "ol10-epel: select takes the highest verified u<N> when self-minor is absent"
  osminor=""
  got="$(printf 'ol10_developer_EPEL\t1\nol10_u1_developer_EPEL\t1\n' | _ol10_epel_select)"
  assert_eq "ol10_u1_developer_EPEL" "${got}" \
    "ol10-epel: an unversioned section ranks below any versioned one"
  got="$(printf 'ol10_developer_EPEL\t1\nol10_u1_developer_EPEL\t0\n' | _ol10_epel_select)"
  assert_eq "ol10_developer_EPEL" "${got}" \
    "ol10-epel: an unversioned section wins as the sole survivor (best_n=-2 sentinel regression pin)"
  rc=0
  printf 'ol10_u1_developer_EPEL\t0\n' | _ol10_epel_select >/dev/null || rc=1
  assert_eq "1" "${rc}" \
    "ol10-epel: select returns rc 1 when nothing verified"

  # (b4) orchestrator with a stubbed probe (no network): the verdict table is
  # keyed by URL, mirroring the four container-FT scenarios of 2026-07-16.
  _ol10_epel_probe() {
    case "$1" in
      *"${PROBE_ALIVE_1:-@nope@}"*) return 0 ;;
      *"${PROBE_ALIVE_2:-@nope@}"*) return 0 ;;
      *) return 1 ;;
    esac
  }

  # (b4a) shipped u1 alive, constructed u2 dead (today's 10.2 lag): shipped
  # section selected, dead u0 explicitly disabled, no disposable.
  osminor=2
  PROBE_ALIVE_1="/OL10/1/"; PROBE_ALIVE_2=""
  OL10_EPEL_DISPOSABLE=""
  rc=0; setup_epel_ol10 >/dev/null || rc=1
  assert_eq "0" "${rc}" "ol10-epel: orchestrator succeeds in the 10.2-lag scenario"
  assert_match "$(sed -n '/^\[ol10_u0_developer_EPEL\]/,/^\[/p' "${OL10_EPEL_REPO_FILE}")" \
    'enabled=0' "ol10-epel: the dead shipped u0 section is explicitly disabled (D2)"
  assert_match "$(sed -n '/^\[ol10_u1_developer_EPEL\]/,/^\[/p' "${OL10_EPEL_REPO_FILE}")" \
    'enabled=1' "ol10-epel: the live shipped u1 section stays enabled"
  assert_eq "" "${OL10_EPEL_DISPOSABLE}" \
    "ol10-epel: no disposable file when a shipped section wins"

  # (b4b) all shipped sections dead, constructed self-minor alive: disposable
  # materialized (marker + gpgcheck), then cleanup removes it.
  osminor=2
  PROBE_ALIVE_1="/OL10/2/"; PROBE_ALIVE_2=""
  OL10_EPEL_DISPOSABLE=""
  rc=0; setup_epel_ol10 >/dev/null || rc=1
  assert_eq "0" "${rc}" "ol10-epel: orchestrator succeeds via the constructed self-minor candidate"
  assert_eq "${tdir}/olaws-ol10-epel-disposable.repo" "${OL10_EPEL_DISPOSABLE}" \
    "ol10-epel: the disposable path derives from the repo-file directory"
  if [[ -f "${OL10_EPEL_DISPOSABLE}" ]]; then
    t_pass "ol10-epel: the disposable repo file is materialized"
    disp="$(cat "${OL10_EPEL_DISPOSABLE}")"
    assert_match "${disp}" '^\[ol10_u2_developer_EPEL\]$' \
      "ol10-epel: disposable carries the constructed self-minor section"
    assert_match "${disp}" "baseurl=https://yum\.oracle\.com/repo/OracleLinux/OL10/2/developer/EPEL/${arch}/" \
      "ol10-epel: disposable baseurl targets the verified self-minor path"
    assert_match "${disp}" 'gpgcheck=1' "ol10-epel: disposable keeps gpgcheck=1"
    cleanup_ol10_epel_disposable >/dev/null
    if [[ ! -e "${tdir}/olaws-ol10-epel-disposable.repo" ]]; then
      t_pass "ol10-epel: cleanup removes the disposable repo file"
    else
      t_fail "ol10-epel: cleanup removes the disposable repo file"
    fi
  else
    t_fail "ol10-epel: the disposable repo file is materialized"
  fi

  # (b4c) everything dead: rc 1, and nothing is materialized.
  # shellcheck disable=SC2034  # consumed inside the eval'd orchestrator
  osminor=2
  PROBE_ALIVE_1=""; PROBE_ALIVE_2=""
  OL10_EPEL_DISPOSABLE=""
  rc=0; setup_epel_ol10 >/dev/null || rc=1
  assert_eq "1" "${rc}" "ol10-epel: orchestrator returns rc 1 when no candidate verifies"
  if [[ ! -e "${tdir}/olaws-ol10-epel-disposable.repo" ]]; then
    t_pass "ol10-epel: no disposable file on the all-dead path"
  else
    t_fail "ol10-epel: no disposable file on the all-dead path"
  fi
fi

t_done
