"""
wsusscn2 fixture builder for T12 (Phase 2b1 parser pipeline tests).

This module generates a *minimal* package.xml that exercises every
control-flow path in the PowerShell Stage 3 parser
(`ConvertFrom-WsusScnPackageXml`) and the Stage 4 serializer
(`New-WsusScnDependencyDatabase`):

  * scope-filter ADMIT: an in-scope Server 2022 bundle update with full
    Categories/Prerequisites/SupersededBy/Files metadata
  * scope-filter REJECT (product mismatch): an update tagged with a
    non-LTSC product GUID
  * scope-filter REJECT (recency): an update older than the cutoff window
  * Category-Update detection: a <Update> with
    DeploymentAction="Evaluate" + IsSoftware="false" representing the
    Server 2025 LTSC Product Category itself
  * payload-URL join: a non-bundle child update whose FileDigest matches
    an entry in <FileLocations>
  * Microsoft-prose absence: the fixture deliberately contains zero
    <Title>/<Description>/<MoreInfoUrl> elements; the parser's positive
    allowlist is also asserted independently against this fact

The fixture is intentionally small (well under 20 KB) so it can be
committed to the repository and parsed in milliseconds.

The accompanying `expected-output.json` is the canonical-JSON
serialization of the parser result. It is regenerated by running this
module's `main()`; T12 asserts byte-level equality against this file.

This module is invoked manually (not from a test runner) when the
fixture or expected output needs to be updated. Manual invocation
matches the conservative posture of SPEC §B.19.9 — fixture changes
must be reviewed by a human because they encode parser semantics.

Usage:
    python3 -m tests.common.wsusscn2_fixture_builder \
        --out-dir tests/fixtures/wsusscn2

CLI options:
    --out-dir DIR   Write package.xml + expected-output.json here
    --print-only    Print the package.xml to stdout instead of writing
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

# Canonical GUIDs (must match Update-WindowsServerIso.ps1
# $Script:WsusScnOsCategoryGuids and $Script:WsusScnUpdateClassificationGuids,
# which in turn match research §5.7).
GUID_SERVER_2016 = "569e8e8f-c6cd-42c8-92a3-efbb20a0f6f5"
GUID_SERVER_2019 = "f702a48c-919b-45d6-9aef-ca4248d50397"
GUID_SERVER_2022 = "71718f13-7324-4b0f-8f9e-2ca9dc978e53"
GUID_SERVER_2025 = "ca006cfb-49eb-439b-880a-1312e1fc9713"

GUID_CLASS_SECURITY = "0fa1201d-4330-4fa8-8ae9-b877473b6441"
GUID_CLASS_ROLLUPS = "28bc880e-0592-4cbf-8f95-c79b17911d5f"
GUID_CLASS_SERVICEPACKS = "68c5b0a3-d1a6-4553-ae49-01d3a7827828"

GUID_COMPANY_MICROSOFT = "56309036-4c77-4dd9-951a-99ee9c246a94"
GUID_FAMILY_WINDOWS = "6964aab4-c5b5-43bd-a17d-ffb4346a8e1d"

# Out-of-scope GUID used for negative test (rejected by Product filter)
GUID_OFFICE = "477b856e-65c4-4473-b621-a8b230bb70d9"

# Pinned "now" for deterministic recency assertions.
# The fixture's CreationDate values are chosen relative to this anchor.
PINNED_NOW = "2026-05-28T00:00:00Z"

# Fixture Updates: each (UpdateId, RevisionId, CreationDate, attrs..., metadata)
# These are deliberately fabricated GUIDs in the f0/f1/f2/... namespace so
# they cannot collide with any real wsusscn2 record by accident.
_BUNDLE_S2022_REVID = "990001"
_CHILD_S2022_REVID  = "990002"
_BUNDLE_S2025_REVID = "990003"
_CATEGORY_S2025_REVID = "990004"
_OOS_OFFICE_REVID   = "990005"
_OLD_S2019_REVID    = "990006"

# File digests (must be unique strings; not real SHA-256 because the
# fixture does not need to validate against actual file content)
_DIGEST_S2022_LCU = "fixture-digest-aaaa"
_DIGEST_S2025_LCU = "fixture-digest-bbbb"
_DIGEST_ORPHAN    = "fixture-digest-cccc"   # in <Files> but not in <FileLocations>

# Payload URLs (returned by the FileLocation join)
_URL_S2022_LCU = "http://example.invalid/fixture/server2022-lcu.cab"
_URL_S2025_LCU = "http://example.invalid/fixture/server2025-lcu.cab"


def build_package_xml() -> str:
    """Construct the package.xml content as a Python str.

    Returned XML has no Microsoft-prose elements (no <Title>, no
    <Description>, no <MoreInfoUrl>). This is verified by the
    accompanying T12 test.
    """
    parts: list[str] = []
    parts.append('<?xml version="1.0" encoding="utf-8"?>')
    parts.append(
        '<OfflineSyncPackage xmlns="http://schemas.microsoft.com/msus/2004/02/OfflineSync"'
        ' MinimumClientVersion="5.8.0.2678"'
        ' PackageId="fixture-pkg-uuid"'
        ' ProtocolVersion="1.20"'
        ' SourceId="fixture-src-uuid">'
    )

    parts.append('<Updates>')

    # 1. In-scope Server 2022 bundle update (admitted by scope filter)
    parts.append(_render_update(
        update_id="f0000001-0000-0000-0000-000000000001",
        revision_id=_BUNDLE_S2022_REVID,
        revision_number="100",
        creation_date="2026-04-15T10:00:00Z",
        is_bundle=True,
        is_software=True,
        kb_articles=["5099001"],
        categories=[
            ("Product", GUID_SERVER_2022),
            ("UpdateClassification", GUID_CLASS_SECURITY),
            ("Company", GUID_COMPANY_MICROSOFT),
            ("ProductFamily", GUID_FAMILY_WINDOWS),
        ],
        prerequisites=[GUID_CLASS_SERVICEPACKS],
        superseded_by=[],
        bundled_by=[],
        file_digests=[],
    ))

    # 2. Child update of the bundle (carries the actual payload digest)
    #    Bundled-by points to the bundle above
    parts.append(_render_update(
        update_id="f0000001-0000-0000-0000-000000000002",
        revision_id=_CHILD_S2022_REVID,
        revision_number="100",
        creation_date="2026-04-15T10:00:00Z",
        is_bundle=False,
        is_software=True,
        kb_articles=[],
        categories=[
            ("Product", GUID_SERVER_2022),
            ("UpdateClassification", GUID_CLASS_SECURITY),
        ],
        prerequisites=[],
        superseded_by=[],
        bundled_by=[_BUNDLE_S2022_REVID],
        file_digests=[_DIGEST_S2022_LCU],
    ))

    # 3. In-scope Server 2025 bundle update (admitted)
    parts.append(_render_update(
        update_id="f0000001-0000-0000-0000-000000000003",
        revision_id=_BUNDLE_S2025_REVID,
        revision_number="100",
        creation_date="2026-05-10T10:00:00Z",
        is_bundle=True,
        is_software=True,
        kb_articles=["5099003"],
        categories=[
            ("Product", GUID_SERVER_2025),
            ("UpdateClassification", GUID_CLASS_SECURITY),
        ],
        prerequisites=[],
        superseded_by=[],
        bundled_by=[],
        file_digests=[_DIGEST_S2025_LCU, _DIGEST_ORPHAN],
    ))

    # 4. Category Update (DeploymentAction="Evaluate" + IsSoftware="false")
    #    Should be REJECTED because IsSoftware="false" and the
    #    UpdateClassification is missing — i.e. the scope filter requires
    #    both Product and Classification.
    parts.append(_render_update(
        update_id=GUID_SERVER_2025,
        revision_id=_CATEGORY_S2025_REVID,
        revision_number="50",
        creation_date="2020-12-03T18:44:45Z",
        is_bundle=False,
        is_software=False,
        deployment_action="Evaluate",
        kb_articles=[],
        categories=[],  # Categories self-reference would be circular
        prerequisites=[GUID_FAMILY_WINDOWS],
        superseded_by=[],
        bundled_by=[],
        file_digests=[],
    ))

    # 5. Out-of-scope (Office product) update — REJECTED by Product filter
    parts.append(_render_update(
        update_id="f0000001-0000-0000-0000-000000000005",
        revision_id=_OOS_OFFICE_REVID,
        revision_number="100",
        creation_date="2026-04-15T10:00:00Z",
        is_bundle=False,
        is_software=True,
        kb_articles=["5099005"],
        categories=[
            ("Product", GUID_OFFICE),
            ("UpdateClassification", GUID_CLASS_SECURITY),
        ],
        prerequisites=[],
        superseded_by=[],
        bundled_by=[],
        file_digests=[],
    ))

    # 6. Old in-scope (Server 2019) update — REJECTED by recency filter
    #    (older than 24 months before PINNED_NOW = 2026-05-28)
    parts.append(_render_update(
        update_id="f0000001-0000-0000-0000-000000000006",
        revision_id=_OLD_S2019_REVID,
        revision_number="100",
        creation_date="2022-01-15T10:00:00Z",
        is_bundle=False,
        is_software=True,
        kb_articles=["5099006"],
        categories=[
            ("Product", GUID_SERVER_2019),
            ("UpdateClassification", GUID_CLASS_ROLLUPS),
        ],
        prerequisites=[],
        superseded_by=[],
        bundled_by=[],
        file_digests=[],
    ))

    parts.append('</Updates>')

    # FileLocations section: two of three child digests resolve to URLs;
    # _DIGEST_ORPHAN is intentionally left out so the parser stats can
    # show a non-zero "payloadUrlsMissing" count.
    parts.append('<FileLocations>')
    parts.append(
        f'<FileLocation Id="1" FileDigest="{_DIGEST_S2022_LCU}">'
        f'<Url>{_URL_S2022_LCU}</Url></FileLocation>'
    )
    parts.append(
        f'<FileLocation Id="2" FileDigest="{_DIGEST_S2025_LCU}">'
        f'<Url>{_URL_S2025_LCU}</Url></FileLocation>'
    )
    parts.append('</FileLocations>')

    parts.append('</OfflineSyncPackage>')
    return '\n'.join(parts) + '\n'


def _render_update(
    *,
    update_id: str,
    revision_id: str,
    revision_number: str,
    creation_date: str,
    is_bundle: bool,
    is_software: bool,
    kb_articles: list[str],
    categories: list[tuple[str, str]],
    prerequisites: list[str],
    superseded_by: list[str],
    bundled_by: list[str],
    file_digests: list[str],
    deployment_action: str | None = None,
) -> str:
    """Render a single <Update> element."""
    attrs = [
        f'UpdateId="{update_id}"',
        f'RevisionId="{revision_id}"',
        f'RevisionNumber="{revision_number}"',
        f'CreationDate="{creation_date}"',
        f'DefaultLanguage="en"',
        f'IsBundle="{str(is_bundle).lower()}"',
        f'IsSoftware="{str(is_software).lower()}"',
    ]
    if deployment_action:
        attrs.append(f'DeploymentAction="{deployment_action}"')

    children: list[str] = []
    for kb in kb_articles:
        children.append(f'<KBArticleID>{kb}</KBArticleID>')
    if categories:
        children.append('<Categories>')
        for ctype, cid in categories:
            children.append(f'<Category Type="{ctype}" Id="{cid}" />')
        children.append('</Categories>')
    if prerequisites:
        children.append('<Prerequisites>')
        for uid in prerequisites:
            children.append(f'<UpdateId Id="{uid}" />')
        children.append('</Prerequisites>')
    if superseded_by:
        children.append('<SupersededBy>')
        for uid in superseded_by:
            children.append(f'<UpdateId Id="{uid}" />')
        children.append('</SupersededBy>')
    if bundled_by:
        children.append('<BundledBy>')
        for rid in bundled_by:
            children.append(f'<RevisionId Id="{rid}" />')
        children.append('</BundledBy>')
    if file_digests:
        children.append('<Files>')
        for d in file_digests:
            children.append(f'<File Digest="{d}" />')
        children.append('</Files>')

    if not children:
        return f'<Update {" ".join(attrs)} />'
    return f'<Update {" ".join(attrs)}>{"".join(children)}</Update>'


def build_expected_output() -> dict[str, Any]:
    """Construct the expected parser output as a Python dict.

    Mirrors what `ConvertFrom-WsusScnPackageXml` + `New-WsusScnDependencyDatabase`
    will produce when invoked against the package.xml from
    `build_package_xml()` with `RecencyMonths=24` and `Now=PINNED_NOW`.

    Note: the `_meta.scriptVersion`, `_meta.scriptTag`, `_meta.generatedAt`,
    and `_meta.sourceCab` fields are environmental and excluded from the
    expected output (T12 strips them before comparison).
    """
    return {
        "_meta": {
            "scope": {
                "productGuids": [
                    GUID_SERVER_2016, GUID_SERVER_2019, GUID_SERVER_2022, GUID_SERVER_2025,
                ],
                "classificationGuids": [
                    GUID_CLASS_SECURITY, GUID_CLASS_ROLLUPS, GUID_CLASS_SERVICEPACKS,
                    "e6cf1350-c01b-414d-a61f-263d14d133b4",
                    "cd5ffd1e-e932-4e3a-bf74-18bf0b1bbd83",
                ],
                "recencyMonths": 24,
                "now": PINNED_NOW,
            },
            "stats": {
                "updatesObserved": 6,
                "updatesInScope": 3,
                "bundlesObserved": 2,
                "categoryUpdates": 1,
                "fileLocationsObserved": 2,
                "fileLocationsRetained": 2,
                "payloadUrlsMissing": 1,
            },
        },
        "updates": [
            {
                "updateId": "f0000001-0000-0000-0000-000000000001",
                "revisionId": _BUNDLE_S2022_REVID,
                "revisionNumber": "100",
                "creationDate": "2026-04-15T10:00:00Z",
                "isBundle": True,
                "isSoftware": True,
                "deploymentAction": None,
                "kbArticleIds": ["5099001"],
                "productGuids": [GUID_SERVER_2022],
                "classificationGuids": [GUID_CLASS_SECURITY],
                "companyGuids": [GUID_COMPANY_MICROSOFT],
                "productFamilyGuids": [GUID_FAMILY_WINDOWS],
                "prerequisiteUpdateIds": [GUID_CLASS_SERVICEPACKS],
                "supersededByUpdateIds": [],
                "bundledByRevisionIds": [],
                "payloadFileDigests": [],
                "payloadUrls": [],
            },
            {
                "updateId": "f0000001-0000-0000-0000-000000000002",
                "revisionId": _CHILD_S2022_REVID,
                "revisionNumber": "100",
                "creationDate": "2026-04-15T10:00:00Z",
                "isBundle": False,
                "isSoftware": True,
                "deploymentAction": None,
                "kbArticleIds": [],
                "productGuids": [GUID_SERVER_2022],
                "classificationGuids": [GUID_CLASS_SECURITY],
                "companyGuids": [],
                "productFamilyGuids": [],
                "prerequisiteUpdateIds": [],
                "supersededByUpdateIds": [],
                "bundledByRevisionIds": [_BUNDLE_S2022_REVID],
                "payloadFileDigests": [_DIGEST_S2022_LCU],
                "payloadUrls": [_URL_S2022_LCU],
            },
            {
                "updateId": "f0000001-0000-0000-0000-000000000003",
                "revisionId": _BUNDLE_S2025_REVID,
                "revisionNumber": "100",
                "creationDate": "2026-05-10T10:00:00Z",
                "isBundle": True,
                "isSoftware": True,
                "deploymentAction": None,
                "kbArticleIds": ["5099003"],
                "productGuids": [GUID_SERVER_2025],
                "classificationGuids": [GUID_CLASS_SECURITY],
                "companyGuids": [],
                "productFamilyGuids": [],
                "prerequisiteUpdateIds": [],
                "supersededByUpdateIds": [],
                "bundledByRevisionIds": [],
                "payloadFileDigests": [_DIGEST_S2025_LCU, _DIGEST_ORPHAN],
                "payloadUrls": [_URL_S2025_LCU],
            },
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("tests/fixtures/wsusscn2"),
        help="Output directory for package.xml + expected-output.json",
    )
    parser.add_argument(
        "--print-only",
        action="store_true",
        help="Print package.xml to stdout instead of writing files",
    )
    args = parser.parse_args()

    xml_text = build_package_xml()
    expected = build_expected_output()

    if args.print_only:
        sys.stdout.write(xml_text)
        return 0

    args.out_dir.mkdir(parents=True, exist_ok=True)
    xml_path = args.out_dir / "package.xml"
    json_path = args.out_dir / "expected-output.json"

    xml_path.write_bytes(xml_text.encode("utf-8"))

    # Write expected-output.json using the project's canonical formatter
    from tests.common.canonical_json import save_canonical_json_file
    save_canonical_json_file(expected, json_path, depth=32)

    print(f"Wrote {xml_path} ({xml_path.stat().st_size:,} bytes)")
    print(f"Wrote {json_path} ({json_path.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
